format_version: 10
pipelines:
  Expense-tf-destroy:
    group: Terraform
    materials:
      git-b844969:
        git: https://github.com/DevOps-iteration2/expense-terraform.git
        shallow_clone: false
        auto_update: true
        branch: main
    secure_variables:
      TF_VAR_vault_token: AES:IWO2eIk5NdLv3ah3Ubth3Q==:LwHJKINlIGdl/nzBDybgTPDx/4zBQwBNmKqvJJcWY7U=
    stages:
      - DEV:
          fetch_materials: true
          environment_variables:
            env : dev
          approval:
            type: manual
          jobs:
            terraform-destroy:
              tasks:
                - exec: {command: "terraform", arguments: [ "init","-backend-config=env-dev/state.tfvars" ], run_if: passed}
                - exec: {command: "terraform", arguments: [ "destroy", "-var-file=env-dev/main.tfvars" ], run_if: passed}