variable "env" {}
variable "instance_type" {}
variable "component" {}
variable "app_port" {}
variable "vpc_id" {}
variable "lb_type" {}
variable "lb_subnets" {}
variable "certificate_arn" {}
variable "lb_ports" {}
variable "lb_app_port_sg_cidr" {}
variable "max_capacity" {}
variable "min_capacity" {}
variable "server_app_port_sg_cidr" {}
variable "prometheus_nodes" {}
variable "bastion_nodes" {}
variable "subnets" {}
variable "vault_token" {}
variable "zone_id" {}